statements = { label | relation }+ $;
label = id:identifier ("." cls:CLASS | ".")  label:string ;
relation = source:and_stmt "->" destination:identifier NEWLINE ;
and_stmt = @:identifier {"and" @:identifier} ;

identifier = /\d*/ ;
string = /.*/ ;

NEWLINE = /\n/ ;
CLASS = "inj" | "obs" ;
